--------------------------------------------------------
--  DDL for Table ADDRESS_TYPE
--------------------------------------------------------

  CREATE TABLE "CMS"."ADDRESS_TYPE"
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE ,
	"NAME" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP",
	"CREATED_DATE" TIMESTAMP (6),
	"UPDATED_DATE" TIMESTAMP (6),
	"IS_DELETED" CHAR(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'N'
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ADDRESS_TYPE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CMS"."ADDRESS_TYPE_PK" ON "CMS"."ADDRESS_TYPE" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ADDRESS_TYPE
--------------------------------------------------------

  ALTER TABLE "CMS"."ADDRESS_TYPE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "CMS"."ADDRESS_TYPE" ADD CONSTRAINT "ADDRESS_TYPE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS"  ENABLE;
