--------------------------------------------------------
--  DDL for Table ADDRESS
--------------------------------------------------------

  CREATE TABLE "CMS"."ADDRESS"
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE ,
	"STREET" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP",
	"LOCALITY" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP",
	"AREA" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP",
	"PINCODE" NUMBER,
	"CREATED_DATE" TIMESTAMP (6),
	"UPDATED_DATE" TIMESTAMP (6),
	"ADDRESS_TYPE_ID" NUMBER,
	"CUSTOMER_ID" NUMBER,
	"CITY_ID" NUMBER,
	"STATE_ID" NUMBER,
	"COUNTRY_ID" NUMBER,
	"IS_DELETED" CHAR(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'N'
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ADDRESS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CMS"."ADDRESS_PK" ON "CMS"."ADDRESS" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ADDRESS
--------------------------------------------------------

  ALTER TABLE "CMS"."ADDRESS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "CMS"."ADDRESS" ADD CONSTRAINT "ADDRESS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CMS"."ADDRESS" MODIFY ("CUSTOMER_ID" NOT NULL ENABLE);
  ALTER TABLE "CMS"."ADDRESS" MODIFY ("CITY_ID" NOT NULL ENABLE);
  ALTER TABLE "CMS"."ADDRESS" MODIFY ("STATE_ID" NOT NULL ENABLE);
  ALTER TABLE "CMS"."ADDRESS" MODIFY ("COUNTRY_ID" NOT NULL ENABLE);
  ALTER TABLE "CMS"."ADDRESS" MODIFY ("ADDRESS_TYPE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ADDRESS
--------------------------------------------------------

  ALTER TABLE "CMS"."ADDRESS" ADD CONSTRAINT "ADDRESS_FK1" FOREIGN KEY ("ADDRESS_TYPE_ID")
	  REFERENCES "CMS"."ADDRESS_TYPE" ("ID") ENABLE;
  ALTER TABLE "CMS"."ADDRESS" ADD CONSTRAINT "ADDRESS_FK2" FOREIGN KEY ("CUSTOMER_ID")
	  REFERENCES "CMS"."CUSTOMER" ("ID") ENABLE;
  ALTER TABLE "CMS"."ADDRESS" ADD CONSTRAINT "ADDRESS_FK3" FOREIGN KEY ("CITY_ID")
	  REFERENCES "CMS"."CITY" ("ID") ENABLE;
  ALTER TABLE "CMS"."ADDRESS" ADD CONSTRAINT "ADDRESS_FK4" FOREIGN KEY ("STATE_ID")
	  REFERENCES "CMS"."STATE" ("ID") ENABLE;
  ALTER TABLE "CMS"."ADDRESS" ADD CONSTRAINT "ADDRESS_FK5" FOREIGN KEY ("COUNTRY_ID")
	  REFERENCES "CMS"."COUNTRY" ("ID") ENABLE;
