--------------------------------------------------------
--  DDL for Table CUSTOMER
--------------------------------------------------------

  CREATE TABLE "CMS"."CUSTOMER"
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE ,
	"NAME" VARCHAR2(70 BYTE) COLLATE "USING_NLS_COMP",
	"DOB" TIMESTAMP (6),
	"GENDER" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP",
	"MOBILE_NO" NUMBER,
	"EMAIL" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP",
	"CREATED_DATE" TIMESTAMP (6),
	"UPDATED_DATE" TIMESTAMP (6),
	"CUSTOMER_STATUS_ID" NUMBER,
	"IS_DELETED" CHAR(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'N'
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CUSTOMER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CMS"."CUSTOMER_PK" ON "CMS"."CUSTOMER" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CUSTOMER
--------------------------------------------------------

  ALTER TABLE "CMS"."CUSTOMER" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "CMS"."CUSTOMER" ADD CONSTRAINT "CUSTOMER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CMS"."CUSTOMER" MODIFY ("CUSTOMER_STATUS_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CUSTOMER
--------------------------------------------------------

  ALTER TABLE "CMS"."CUSTOMER" ADD CONSTRAINT "CUSTOMER_FK1" FOREIGN KEY ("CUSTOMER_STATUS_ID")
	  REFERENCES "CMS"."CUSTOMER_STATUS" ("ID") ENABLE;
