--------------------------------------------------------
--  DDL for Table USER_PREFERENCES
--------------------------------------------------------

  CREATE TABLE "CMS"."USER_PREFERENCES"
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE ,
	"USER_ID" NUMBER,
	"PAGE_NAME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index USER_PREFERENCES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CMS"."USER_PREFERENCES_PK" ON "CMS"."USER_PREFERENCES" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table USER_PREFERENCES
--------------------------------------------------------

  ALTER TABLE "CMS"."USER_PREFERENCES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "CMS"."USER_PREFERENCES" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "CMS"."USER_PREFERENCES" MODIFY ("PAGE_NAME" NOT NULL ENABLE);
  ALTER TABLE "CMS"."USER_PREFERENCES" ADD CONSTRAINT "USER_PREFERENCES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USER_PREFERENCES
--------------------------------------------------------

  ALTER TABLE "CMS"."USER_PREFERENCES" ADD CONSTRAINT "FK_USER_PREFS_USERS" FOREIGN KEY ("USER_ID")
	  REFERENCES "CMS"."USERS" ("ID") ENABLE;
